CREATE TABLE IF NOT EXISTS conta (
	id BIGINT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(60) NOT NULL,
	email VARCHAR(255) NOT NULL,
	login VARCHAR(20) NOT NULL,
    senha VARCHAR(20) NOT NULL,
	
	PRIMARY KEY (id)
);